(function () {
  'use strict';
  const eq = Bench.equation, tex = Bench.tex, tint = Bench.tint, mark = Bench.mark;
  const $ = id => document.getElementById(id);
  const fmt = RF.formatNumber, freq = hz => RF.formatFrequency(hz).text;
  const metric = (label, value, cls) => `<div class="metric${cls ? ' ' + cls : ''}"><dt>${label}</dt><dd>${value}</dd></div>`;
  const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const SCALES = { Hz: 1, kHz: 1e3, MHz: 1e6, GHz: 1e9 };
  const KINDS = { dd: ['diff', 'diff'], sd: ['diff', 'se'], ds: ['se', 'diff'], ss: ['se', 'se'] };
  const TOPOLOGY_OF = { diff: { diff: 'dd', se: 'sd' }, se: { diff: 'ds', se: 'ss' } };
  const LABELS = { dd: 'differential in, differential out', sd: 'differential in, single-ended out', ds: 'single-ended in, differential out', ss: 'single-ended in, single-ended out' };
  let file = null, fileName = '', index = 0, plotOf = '', wanted = NaN;
  const mapping = { in: [1, 3], out: [2, 4] };

  // ---------- A built-in example so the page reads something before a file is dropped: a
  // lossy differential line pair with a little skew and modest return loss, 100 MHz to 50 GHz.
  function exampleText() {
    const lines = ['! Example: differential line pair, generated by RF Lab Reference', '# GHz S RI R 50'];
    const points = 100, alpha = 0.06, tau = 150e-12, skew = 3e-12;
    const polar = (mag, rad) => [mag * Math.cos(rad), mag * Math.sin(rad)];
    for (let k = 0; k < points; k++) {
      const f = 0.1e9 + k * (49.9e9 / (points - 1)), fg = f / 1e9;
      const loss = Math.pow(10, -alpha * Math.sqrt(fg) * 4 / 20);
      const t21 = polar(loss, -2 * Math.PI * f * tau), t43 = polar(loss * 0.985, -2 * Math.PI * f * (tau + skew));
      const refl = polar(0.1 + 0.002 * fg, 2 * Math.PI * f * tau * 0.4), cross = polar(0.01 * fg / 10, Math.PI / 3);
      const S = { 1: { 1: refl, 2: t21, 3: cross, 4: cross }, 2: { 1: t21, 2: refl, 3: cross, 4: cross }, 3: { 1: cross, 2: cross, 3: refl, 4: t43 }, 4: { 1: cross, 2: cross, 3: t43, 4: refl } };
      for (let i = 1; i <= 4; i++) lines.push((i === 1 ? fg.toFixed(4) + ' ' : '  ') + [1, 2, 3, 4].map(j => S[i][j].map(v => v.toFixed(6)).join(' ')).join('  '));
    }
    return lines.join('\n');
  }

  // ---------- Topology from the DUT card; logical ports from the mapping.
  const topology = () => { const d = Dut.get(); return TOPOLOGY_OF[d.din][d.dout]; };
  function sides() {
    const [kin, kout] = KINDS[topology()];
    return [{ ports: kin === 'diff' ? mapping.in.slice(0, 2) : [mapping.in[0]] }, { ports: kout === 'diff' ? mapping.out.slice(0, 2) : [mapping.out[0]] }];
  }
  const mixedPossible = () => file && file.ports >= 3 && sides().flatMap(s => s.ports).every(p => p <= file.ports) && Boolean(RF.mixedModeRows(sides()));
  const throughName = () => {
    if (!file || file.ports < 3 || !mixedPossible()) return 'S21';
    const [kin, kout] = KINDS[topology()];
    return `S${kout === 'diff' ? 'd' : 's'}${kin === 'diff' ? 'd' : 's'}21`;
  };
  const show = v => v.mag > 0 ? `${fmt(v.db, 'dB')} dB ∠ ${fmt(v.deg, 'deg')}°` : '−∞ dB';
  function valueAt(point, name) {
    const se = name.match(/^S(\d)(\d)$/);
    if (se) return RF.toPolar(point.S[Number(se[1])][Number(se[2])]);
    const m = RF.mixedMode(point.S, sides());
    return m && m.byName[name] ? m.byName[name].value : null;
  }
  function nearestIndex(hz) {
    let best = 0;
    file.points.forEach((p, i) => { if (Math.abs(p.f - hz) < Math.abs(file.points[best].f - hz)) best = i; });
    return best;
  }

  // ---------- Link: the frequency, the mapping and the plot choice; never the file.
  function readQuery() {
    const q = new URLSearchParams(location.search);
    const f = RF.parseFrequency(q.get('f'), 1);
    if (f > 0) wanted = f;
    if (Object.hasOwn(SCALES, q.get('fu'))) $('freq-unit').value = q.get('fu');
    if (q.has('plot')) plotOf = q.get('plot');
    for (const [key, side] of [['p1', 'in'], ['p2', 'out']]) {
      if (!q.has(key)) continue;
      const ports = q.get(key).split(',').map(Number);
      if (ports.length === 2 && ports.every(p => Number.isInteger(p) && p >= 1 && p <= 4)) mapping[side] = ports;
    }
  }
  function writeQuery() {
    const q = new URLSearchParams({ f: file ? String(file.points[index].f) : '', fu: $('freq-unit').value, plot: plotOf, p1: mapping.in.join(','), p2: mapping.out.join(',') });
    history.replaceState(null, '', location.pathname + '?' + q);
  }

  // ---------- Reading a file.
  async function load(blob, name) {
    let text;
    try { text = await blob.text(); } catch (_) { return fail('The file could not be read.'); }
    accept(text, name);
  }
  function accept(text, name) {
    const hint = (name.match(/\.s(\d)p$/i) || [])[1];
    const parsed = RF.parseTouchstone(text, hint ? Number(hint) : undefined);
    if (parsed.error) return fail(parsed.error);
    file = parsed; fileName = name;
    $('point').max = String(file.points.length - 1);
    index = Number.isFinite(wanted) ? nearestIndex(wanted) : Math.floor(file.points.length / 2);
    wanted = NaN;
    $('file-status').textContent = ''; $('file-status').className = '';
    fillPlotChoices(); renderMapping(); render();
  }
  function fail(message) {
    $('file-status').textContent = message; $('file-status').className = 'status-error';
  }
  function fillPlotChoices() {
    const names = [];
    for (let i = 1; i <= file.ports; i++) for (let j = 1; j <= file.ports; j++) names.push(`S${i}${j}`);
    if (mixedPossible()) RF.mixedMode(file.points[0].S, sides()).entries.forEach(e => names.push(e.name));
    if (!names.includes(plotOf)) plotOf = names.includes(throughName()) ? throughName() : names[0];
    $('plot-of').innerHTML = names.map(n => `<option value="${n}"${n === plotOf ? ' selected' : ''}>${n}</option>`).join('');
  }
  function renderMapping() {
    const [kin, kout] = KINDS[topology()];
    const select = (side, i, label, cls) => `<label class="${cls}"><span>${label}</span><select data-side="${side}" data-index="${i}" aria-label="${label}">${
      Array.from({ length: file.ports }, (_, k) => `<option value="${k + 1}"${mapping[side][i] === k + 1 ? ' selected' : ''}>Port ${k + 1}</option>`).join('')}</select></label>`;
    $('mapping').innerHTML =
      (kin === 'diff' ? select('in', 0, 'Logical port 1, positive line', 'tint-in') + select('in', 1, 'Logical port 1, negative line', 'tint-in') : select('in', 0, 'Logical port 1, single-ended', 'tint-in')) +
      (kout === 'diff' ? select('out', 0, 'Logical port 2, positive line', 'tint-out') + select('out', 1, 'Logical port 2, negative line', 'tint-out') : select('out', 0, 'Logical port 2, single-ended', 'tint-out'));
  }

  // ---------- The plot: magnitude of one parameter against frequency, marker at the reading.
  function drawPlot() {
    const svg = $('plot');
    const series = file.points.map(p => { const v = valueAt(p, plotOf); return { f: p.f, db: v && v.mag > 0 ? v.db : NaN }; });
    const finite = series.filter(s => Number.isFinite(s.db));
    if (!finite.length) { svg.innerHTML = ''; return; }
    const log = file.last / file.first > 100;
    const x0 = 56, x1 = 668, y0 = 14, y1 = 200;
    const fx = f => log ? x0 + (Math.log10(f / file.first) / Math.log10(file.last / file.first)) * (x1 - x0) : x0 + ((f - file.first) / (file.last - file.first || 1)) * (x1 - x0);
    let lo = Math.min(...finite.map(s => s.db)), hi = Math.max(...finite.map(s => s.db));
    lo = Math.floor((lo - 2) / 5) * 5; hi = Math.ceil((hi + 2) / 5) * 5; if (hi === lo) hi = lo + 5;
    const fy = db => y1 - ((db - lo) / (hi - lo)) * (y1 - y0);
    let out = '';
    const ySteps = 4;
    for (let k = 0; k <= ySteps; k++) {
      const db = lo + (k / ySteps) * (hi - lo), y = fy(db);
      out += `<line class="grid" x1="${x0}" y1="${y.toFixed(1)}" x2="${x1}" y2="${y.toFixed(1)}"/><text x="${x0 - 8}" y="${(y + 4).toFixed(1)}" text-anchor="end">${fmt(db, 'dB')}</text>`;
    }
    const xSteps = Bench.narrow ? 2 : 5;
    for (let k = 0; k <= xSteps; k++) {
      const f = log ? file.first * Math.pow(file.last / file.first, k / xSteps) : file.first + (k / xSteps) * (file.last - file.first), x = fx(f);
      const label = k === 0 || k === xSteps ? freq(f) : freq(Number(f.toPrecision(2)));
      out += `<line class="grid" x1="${x.toFixed(1)}" y1="${y0}" x2="${x.toFixed(1)}" y2="${y1}"/><text x="${x.toFixed(1)}" y="${y1 + 18}" text-anchor="${k === 0 ? 'start' : k === xSteps ? 'end' : 'middle'}">${label}</text>`;
    }
    out += `<rect class="axis" x="${x0}" y="${y0}" width="${x1 - x0}" height="${y1 - y0}"/>`;
    const path = series.map((s, i) => Number.isFinite(s.db) ? `${i === 0 || !Number.isFinite(series[i - 1].db) ? 'M' : 'L'}${fx(s.f).toFixed(1)},${fy(s.db).toFixed(1)}` : '').join(' ');
    out += `<path class="trace" d="${path}"/>`;
    const at = series[index];
    if (Number.isFinite(at.db)) {
      out += `<line class="marker-line" x1="${fx(at.f).toFixed(1)}" y1="${y0}" x2="${fx(at.f).toFixed(1)}" y2="${y1}"/><circle class="marker" cx="${fx(at.f).toFixed(1)}" cy="${fy(at.db).toFixed(1)}" r="5"/>`;
      const right = fx(at.f) > (x0 + x1) / 2;
      out += `<text class="marker-text" x="${(fx(at.f) + (right ? -10 : 10)).toFixed(1)}" y="${Math.max(fy(at.db) - 10, y0 + 12).toFixed(1)}" text-anchor="${right ? 'end' : 'start'}">${fmt(at.db, 'dB')} dB at ${freq(at.f)}</text>`;
    }
    out += `<text x="${x1}" y="${y0 - 2}" text-anchor="end">|${plotOf}| dB${log ? ' · log frequency' : ''}</text>`;
    svg.innerHTML = out;
    svg.setAttribute('aria-label', `Magnitude of ${plotOf} in dB against frequency from ${freq(file.first)} to ${freq(file.last)}, marker at ${freq(at.f)}`);
    $('plot-key').innerHTML = `<span class="key">${plotOf} across the file</span><span class="key key-out">marker · the reading below</span>`;
  }

  // ---------- The reading.
  function render() {
    const reader = $('reader');
    if (!file) { reader.hidden = true; Bench.update({ valid: false, lines: ['Drop a Touchstone file, or load the example, to read it.'] }); return; }
    reader.hidden = false;
    const point = file.points[index], n = file.ports;
    $('point').value = String(index);
    if (document.activeElement !== $('freq')) Bench.setNumber('freq', point.f / SCALES[$('freq-unit').value], '', true);
    $('freq-note').textContent = `Nearest point: ${freq(point.f)}, point ${index + 1} of ${file.points.length}. Nothing is interpolated.`;
    $('file-metrics').innerHTML = metric('File', escape(fileName || 'built-in example')) + metric('Ports', String(n)) +
      metric('Span', `${freq(file.first)} → ${freq(file.last)} · ${file.points.length} points`) + metric('Reference', `${fmt(file.reference)} Ω per port · ${file.format.toUpperCase()}`);
    drawPlot();
    // Single-ended table: row = to, column = from.
    const ports = Array.from({ length: n }, (_, k) => k + 1);
    $('se-head').innerHTML = `<tr><th>to ↓ · from →</th>${ports.map(j => `<th>Port ${j}</th>`).join('')}</tr>`;
    $('se-rows').innerHTML = ports.map(i => `<tr><td>Port ${i}</td>${ports.map(j => `<td class="num">${show(RF.toPolar(point.S[i][j]))}</td>`).join('')}</tr>`).join('');
    // Mixed-mode for the card's topology, when the file has the ports for it.
    const canMix = mixedPossible(), mixed = canMix ? RF.mixedMode(point.S, sides()) : null;
    $('mixed-block').hidden = !(n >= 3);
    if (n >= 3) {
      const valid = RF.mixedModeRows(sides()) && sides().flatMap(s => s.ports).every(p => p <= n);
      $('mapping-status').textContent = valid ? '' : 'Each port can appear once, and every port must exist in the file.'; $('mapping-status').className = valid ? '' : 'status-error';
      if (mixed) {
        const label = r => `<span class="${r.side === 1 ? 'tint-in' : 'tint-out'}">${r.label}</span>`;
        $('mm-head').innerHTML = `<tr><th>to ↓ · from →</th>${mixed.rows.map(r => `<th>${label(r)}</th>`).join('')}</tr>`;
        $('mm-rows').innerHTML = mixed.rows.map((r, ri) => `<tr><td>${r.label}</td>${mixed.rows.map((c, ci) => `<td class="num">${show(mixed.entries[ri * mixed.rows.length + ci].value)}</td>`).join('')}</tr>`).join('');
      } else { $('mm-head').replaceChildren(); $('mm-rows').replaceChildren(); }
    }
    // The through path and its voltage gain under the topology's references.
    const dut = Dut.get(), [kin, kout] = n >= 3 && mixed ? KINDS[topology()] : ['se', 'se'];
    const name = mixed ? throughName() : 'S21', through = n >= 2 ? valueAt(point, name) : null;
    const inName = mixed ? (kin === 'diff' ? 'Sdd11' : 'Sss11') : 'S11', outName = mixed ? (kout === 'diff' ? 'Sdd22' : 'Sss22') : (n >= 2 ? 'S22' : 'S11');
    const reflIn = valueAt(point, inName), reflOut = n >= 2 ? valueAt(point, outName) : null;
    const z1 = kin === 'diff' ? 2 * file.reference : file.reference, z2 = kout === 'diff' ? 2 * file.reference : file.reference;
    const tiles = [];
    let gain = null;
    if (through) {
      const factorDb = 10 * Math.log10(z2 / z1), av = through.db + factorDb;
      const inC = mixed ? RF.mixedMode(point.S, sides()).byName[inName].value : RF.toPolar(point.S[1][1]);
      const denom = Math.hypot(1 + inC.re, inC.im), terminal = denom > 1e-9 ? av - 20 * Math.log10(denom) : NaN;
      gain = { name, z1, z2, factorDb, av, denom, terminal, inName };
      tiles.push(metric(`${name} · through`, show(through), 'primary'),
        metric('Voltage gain', `${fmt(av, 'dB')} dB<span class="metric-sub">20 log|Av| = 20 log|${name}| ${factorDb < 0 ? '−' : '+'} ${fmt(Math.abs(factorDb), 'dB')} dB · ${fmt(z1)} Ω → ${fmt(z2)} Ω</span>`),
        metric('Referred to the input terminal', Number.isFinite(terminal) ? `${fmt(terminal, 'dB')} dB<span class="metric-sub">divides by |1 + ${inName}| = ${fmt(denom)}</span>` : 'Unbounded: the input reflection is −1'));
    }
    if (reflIn) tiles.push(metric(`${inName} · input return`, show(reflIn), 'port-in'));
    if (reflOut) tiles.push(metric(`${outName} · output return`, show(reflOut), 'port-out'));
    if (mixed && kin === 'diff' && kout === 'diff') tiles.push(metric('Scd21 · differential in → common out', show(mixed.byName.Scd21.value)), metric('Sdc21 · common in → differential out', show(mixed.byName.Sdc21.value)));
    $('metrics').innerHTML = tiles.join('');
    Bench.update({ valid: true, lines: [
      `${escape(fileName || 'Built-in example')}: ${n} port${n === 1 ? '' : 's'}, ${file.points.length} points from ${freq(file.first)} to ${freq(file.last)}, ${fmt(file.reference)} Ω reference, ${file.format.toUpperCase()} form. Read at the nearest point, ${freq(point.f)}.`,
      mixed ? `Mixed-mode for ${LABELS[topology()]}: logical port 1 is ${sides()[0].ports.map(p => 'port ' + p).join(' and ')}, logical port 2 is ${sides()[1].ports.map(p => 'port ' + p).join(' and ')}.` : '',
      ...(mixed ? (() => { const e = mixed.byName[name]; const formula = e.terms.map((t, k) => `${t.coefficient < 0 ? '-' : k ? '+' : ''}S_{${t.i}${t.j}}`).join(' '); const c = Math.abs(e.terms[0].coefficient); const pre = Math.abs(c - 0.5) < 1e-9 ? '\\tfrac12' : Math.abs(c - Math.SQRT1_2) < 1e-9 ? '\\tfrac{1}{\\sqrt 2}' : '';
        return [eq('Through parameter from the single-ended set', `${name.replace(/^S(\w\w)(\d)(\d)$/, 'S_{\\mathrm{$1}$2$3}')} &= ${pre ? `${pre}\\left(${formula}\\right)` : formula}`, through.mag > 0 ? `${tex(through.db, 'dB')}\\ \\angle\\ ${tex(through.deg, 'deg')}` : '-\\infty\\,\\mathrm{dB}')]; })() : []),
      ...(gain ? [
        eq('Voltage gain of the through path', `20\\log_{10}|A_v| &= 20\\log_{10}|${gain.name}| + 10\\log_{10}\\frac{${tint('out', 'Z_2')}}{${tint('in', 'Z_1')}}`, tex(gain.av, 'dB'), `${tex(through.db, 'dB', false)} + 10\\log_{10}\\frac{${tint('out', tex(gain.z2, 'Ω'))}}{${tint('in', tex(gain.z1, 'Ω'))}}\\,\\mathrm{dB}`),
        eq('Referred to the input terminal', `\\frac{V_2}{V_1} &= \\frac{${gain.name}}{1+${gain.inName}}\\sqrt{\\frac{Z_2}{Z_1}}`, Number.isFinite(gain.terminal) ? tex(gain.terminal, 'dB') : '\\text{unbounded}', `|1+${gain.inName}| = ${tex(gain.denom)}`),
        'References are the file\'s per-port value, doubled for a differential side. The terminal form uses the reflection from the same point of the file.'] : []),
      'Values are read at the nearest point; nothing is interpolated between points.'
    ].filter(Boolean) });
    writeQuery();
  }

  // ---------- Events.
  const drop = $('drop');
  ['dragenter', 'dragover'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.add('is-over'); }));
  ['dragleave', 'drop'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.remove('is-over'); }));
  drop.addEventListener('drop', event => { const f = event.dataTransfer && event.dataTransfer.files[0]; if (f) load(f, f.name); });
  $('file').addEventListener('change', () => { const f = $('file').files[0]; if (f) load(f, f.name); });
  $('freq').addEventListener('input', () => {
    if (!file) return;
    const hz = RF.parseFrequency($('freq').value, SCALES[$('freq-unit').value]);
    if (hz > 0) { index = nearestIndex(hz); render(); }
  });
  $('freq-unit').addEventListener('change', () => { $('freq').value = RF.frequencyDigits($('freq').value); const hz = RF.parseFrequency($('freq').value, SCALES[$('freq-unit').value]); if (file && hz > 0) index = nearestIndex(hz); if (file) render(); });
  $('point').addEventListener('input', () => { if (!file) return; index = Number($('point').value); render(); });
  $('plot-of').addEventListener('change', () => { plotOf = $('plot-of').value; if (file) render(); });
  $('mapping').addEventListener('change', event => {
    const select = event.target.closest('select[data-side]');
    if (!select) return;
    mapping[select.dataset.side][Number(select.dataset.index)] = Number(select.value);
    fillPlotChoices(); render();
  });
  document.addEventListener('dut-change', () => { if (file) { fillPlotChoices(); renderMapping(); render(); } });
  document.addEventListener('layout-change', () => { if (file) drawPlot(); });
  Dut.describe('the port topology on each side, to build the mixed-mode set and the voltage gain');
  $('copy-link').addEventListener('click', () => { if (Bench.valid) Bench.copy(location.href); });
  $('copy-result').addEventListener('click', () => {
    if (!file) return;
    const point = file.points[index], ports = Array.from({ length: file.ports }, (_, k) => k + 1);
    const lines = [`${fileName || 'Built-in example'} at ${freq(point.f)} | ${file.ports} ports | ${fmt(file.reference)} Ω`];
    ports.forEach(i => lines.push(ports.map(j => `S${i}${j} ${show(RF.toPolar(point.S[i][j]))}`).join(' | ')));
    if (mixedPossible()) { const m = RF.mixedMode(point.S, sides()); m.rows.forEach((r, ri) => lines.push(m.rows.map((c, ci) => { const e = m.entries[ri * m.rows.length + ci]; return `${e.name} ${show(e.value)}`; }).join(' | '))); }
    Bench.copy(lines.join('\n'));
  });
  Bench.exports({ figureTitle: 'Magnitude plot', figure: () => [$('plot'), $('plot-key'), $('metrics')], tableTitle: 'Parameters at this frequency', tables: () => Array.from(document.querySelectorAll('#calc .chain-results')) });
  window.Touchstone = { accept, exampleText };
  readQuery();
  accept(exampleText(), '');
})();
